from datetime import datetime
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[2]

DATASET_DIR = Path("/mnt/ssd/datasets/wuppertal")
HDF_DIR = DATASET_DIR / "hdf"
STATS_PATH = DATASET_DIR / "stats.json"
CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
ESTIMATOR_CHECKPOINT_PATH = CHECKPOINT_DIR / "estimator.pt"
CONFERENCE_DIR = PROJECT_DIR / "conference"

TRAINING_PROVIDER = "wuppertal"
EVALUATION_PROVIDER = "oxford"

RANDOM_SEED = 42

MAX_SEQUENCE_LENGTH = 30000
MIN_SEQUENCE_LENGTH = 1000
CHUNK_SIZE = 2000
WINDOW_SIZE = 1500
WINDOW_STRIDE = 1000

NOMINAL_CAPACITY = 18000.0

VOLTAGE_CHANNEL = "U"
CURRENT_CHANNEL = "I"
TEMPERATURE_CHANNEL = "Temp[1]"
AMBIENT_TEMPERATURE_KEY = "ambient_temperature"
TEMP_DELTA_KEY = "temp_delta"
SOH_KEY = "soh"

CHANNELS = [VOLTAGE_CHANNEL, CURRENT_CHANNEL, TEMPERATURE_CHANNEL]

FEATURE_DISPLAY_NAMES = {
    VOLTAGE_CHANNEL: r"Voltage ($V$)",
    CURRENT_CHANNEL: r"Current ($I$)",
    TEMPERATURE_CHANNEL: r"Cell Temperature ($T$)",
    AMBIENT_TEMPERATURE_KEY: r"Ambient Temperature ($T_{\text{amb}}$)",
    TEMP_DELTA_KEY: r"Thermal Delta ($\Delta T_{\text{cell}}$)",
    SOH_KEY: r"State of Health ($\text{SoH}$)",
}

RASTER_FREQUENCY = 1

REFERENCE_TEMPERATURE = 25.0
REFERENCE_DISCHARGE_RATE = 1.0

TRAINING_MCUS = ["mcu1", "mcu3", "mcu4", "mcu5", "mcu6", "mcu8"]
VALIDATION_MCUS = ["mcu2"]
TESTING_MCUS = ["mcu7"]

AGING_START = datetime(2025, 2, 12)
AGING_END = datetime(2025, 3, 8)
PHASE_ORDER = ["Initial", "Aging", "Post-Aging"]
PROTOCOL_ORDER = ["Constant", "HPPC", "Pulse", "WLTC"]

# soh estimator
ESTIMATOR_INPUT_FEATURES = 3
ESTIMATOR_N_CONDITIONS = 1
ESTIMATOR_BASE_CHANNELS = 64
ESTIMATOR_KERNEL_SIZE = 7
ESTIMATOR_STRIDE = 2
ESTIMATOR_GRU_HIDDEN_SIZE = 128
ESTIMATOR_GRU_N_LAYERS = 2
LEAKY_SLOPE = 0.2

# hyperparams
BATCH_SIZE = 128
EPOCHS = 500
MAX_LEARNING_RATE = 0.001
MIN_LEARNING_RATE = 0.00001
DROPOUT = 0.2
SCHEDULER_PATIENCE = 15
SCHEDULER_FACTOR = 0.5
WEIGHT_DECAY = 0.02
EARLY_STOPPING_PATIENCE = 50

# oxford battery degradation dataset 1
OXFORD_MAT_PATH = DATASET_DIR / "oxford.mat"
OXFORD_HDF_DIR = HDF_DIR / "oxford"
OXFORD_N_CELLS = 8
OXFORD_NOMINAL_CAPACITY_MAH = 740.0
OXFORD_AMBIENT_TEMPERATURE = 40.0
OXFORD_PROTOCOL = PROTOCOL_ORDER[0]
OXFORD_PHASE = PHASE_ORDER[1]
OXFORD_FINE_TUNE_FRACTION = 0.15
OXFORD_BASE_DATETIME = datetime(2015, 1, 8)
OXFORD_MCUS = [f"cell{i}" for i in range(1, OXFORD_N_CELLS + 1)]
