from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_PATH = Path("/mnt/ssd/datasets/wuppertal")
HDF_ROOT = DATA_PATH / "hdf"
STATS_PATH = DATA_PATH / "stats.json"
GENERATOR_CHECKPOINT_PATH = PROJECT_ROOT / "generator.pt"
ESTIMATOR_CHECKPOINT_PATH = PROJECT_ROOT / "estimator.pt"
PLOTS_PATH = PROJECT_ROOT / "plots"

RANDOM_SEED = 42

MAX_SEQUENCE_LENGTH = 15000
CHUNK_SIZE = 2000
WINDOW_SIZE = 2000

NOMINAL_CAPACITY = 18000.0
CHANNELS = ["U", "I", "Temp[1]"]
RASTER_FREQUENCY = 1
REFERENCE_TEMPERATURE_RANGE = (23.0, 27.0)
REFERENCE_CURRENT_RANGE = (4.5, 5.5)

TRAINING_MCUS = ["mcu1", "mcu2", "mcu3", "mcu4", "mcu5", "mcu6"]
VALIDATION_MCUS = ["mcu7"]
TESTING_MCUS = ["mcu8"]

# sequence generator
INPUT_FEATURES = 1
GENERATOR_N_CONDITIONS = 2
HIDDEN_SIZE = 64
N_LAYERS = 2

# soh estimator
INPUT_FEATURES = 3
ESTIMATOR_N_CONDITIONS = 1
CONV_CHANNELS = [256]
CONV_KERNEL_SIZES = [7]
CONV_STRIDES = [2]
GRU_HIDDEN_SIZE = 256
GRU_N_LAYERS = 1

# hyperparams
N_EPOCHS = 200
BATCH_SIZE = 128
LEARNING_RATE = 0.0005
DROPOUT = 0.05
